### ISSUE TITLE
Validate numbers when 0

### ISSUE THREAD

**Issue by yrodrigez** [Eric-Carlton/javascript-object-validator#1]
When required number is 0, the validation is not passed

Sometimes 0 is a valid value

**Comment by Eric-Carlton** [comment]
@yrodrigez Could you give a code sample for this? I'm having trouble replicating. For example, I just tried setting the `age` property for the example object:

`{ name: 'John', age: 0, spouse: { name: 'Jane', age: NaN } }`

And the object was still validated. If I remember correctly, the only default property values that are considered invalid are `undefined` and `null`.

**Comment by Eric-Carlton** [comment]
I also tried setting `a.b.c` to 0 in my unit tests and everything passes:

```
obj = {
    a: {
        b: {
            c: 0,
            d: 'World',
        },
        f: false,
        g: '',
        h: null,
    },
};
```

All unit tests still pass:

```
Started
.........


9 specs, 0 failures
Finished in 0.01 seconds

=============================================================================
Writing coverage object [/Users/ericcarlton/Documents/projects/json-object-validator/coverage/coverage.json]
Writing coverage reports at [/Users/ericcarlton/Documents/projects/json-object-validator/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 100% ( 84/84 )
Branches     : 100% ( 23/23 )
Functions    : 100% ( 2/2 )
Lines        : 100% ( 83/83 )
================================================================================
```

The only way that I can make a value of 0 not validate is to add 0 to the `invalidProperties` array of  a propertyDescriptor.

**Comment by yrodrigez** [comment]
Hello Eric, i'm sorry, you're right. my bad

**Comment by Eric-Carlton** [comment]
Not a problem!
